### ISSUE TITLE
Replacing  manager.configuration.serviceBaseUrl

### ISSUE THREAD

**Issue by jessycormier** [trogers-twilio/plugin-external-conference-warm-transfer#6]
It would seem updates to Twilio's services/functions/flex has left a lot of broken things. While we have this ` this.serviceBaseUrl = manager.configuration.serviceBaseUrl;` manually replaced instead of it being dynamic, I'm wondering if you know of a way to grab the function services URI programmatically?

**Comment by deekshaa8** [comment]
@jessycormier After entering external phone number, nothing happens. call is not getting connected

**Comment by jessycormier** [comment]
This was a long time ago now; We had to do a lot of messing around with things to even get this to work. I'm sorry but I won't be able to provide any help now since I've moved on from this project. As well I'll be closing off this ticket since it's not relevant.

**Comment by deekshaa8** [comment]
Can you just give me some suggestions

**Comment by jessycormier** [comment]
Your question isn't related to what this issue is about so I'm not sure what you're even referring to.

**Comment by deekshaa8** [comment]
The issue is after entering the number call is not getting connected
